### ISSUE TITLE
Clarification on using the Maven Plugin

### ISSUE THREAD

**Issue by durga083** [bsorrentino/maven-confluence-plugin#106]
Hi,

I was exploring code in this plugin and I am impressed with the way its written. I did explore different ways to upload documentation to confluence and I found this is the simplest way where we can post our project related documentation to confluence.

Currently I am looking for a way to post maven project rest api documentation. Can I modify this code and use?

Please provide your inputs.

Thanks,
Durga.

**Comment by bsorrentino** [comment]
Hi, thx for interest

There are several way to accomplish such task. 

**The main goal is to find out stuff that allow you to generate text document (eg markdown) from your api** , after that will be pretty straightforward publish it to confluence using **maven-confluence-plugin**.

While ago I developed a [Java Annotation Processor](http://hannesdorfmann.com/annotation-processing/annotationprocessing101) that will generate wiki from JAXRS annotations.

One of most popular tool to document REST API (not only for that) is [swagger](http://swagger.io/) and i've find out that there is a [markdown converter](https://github.com/Swagger2Markup/swagger2markup)

Hope this help

**Comment by durga083** [comment]
Thanks for responding!

I was looking at swagger also, but I see that for some applications which are already developed, integration with swagger takes some time. Also, I see that including swagger is a different approach where API layer can't be modified and YAML need to be learnt. There might be issue with YAML even because of the space (I mean format issue).

The one which I am trying right now is with out Swagger implementation, for existing apps how can I post REST API documentation to confluence. Annotations are not used in our project , but I will check on Java Annotation Processor. Thanks for the suggestion.

Using maven-confluence-plugin I see that we can only publish maven generated Project Summary (PS: Please correct me if I am wrong). 

Below are my thoughts (Your inputs are greatly appreciated)...

For uploading any user defined like REST API documentation to confluence, I was trying to create new Renderer(eg: RestApiDocumentationRenderer) where I will be writing code to render the table format as per Rest API standards in confluence. This new renderer I am planning to use in the new Deploy Pojo which I will be creating.

Now I can generate jar file with these changes in maven-confluence-plugin and use in any project to publish Rest API to confluence.

Open Item: Now the open Item I will be having is... how to input the API Document to this new renderer based on the project included. This I can try using  Java Annotation Processor or any different way.

Thanks & Regards,
Durga.

**Comment by bsorrentino** [comment]
Hi 

Firstly, **the publication is not limited at "project summary"**  but you can publish what you prefer as long as you have it available either in wiki or markdown format. Please refer to [Site Guide](http://bsorrentino.github.io/maven-confluence-plugin/site_guide.html)

If you prefer we could continue this interesting discussion on gitter [![Join the chat at https://gitter.im/bsorrentino/maven-confluence-plugin](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/bsorrentino/maven-confluence-plugin?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by durga083** [comment]
Thanks for the inputs. I will check on this and will join the chat in gitter.
