### ISSUE TITLE
Sublist support

### ISSUE THREAD

**Issue by esivres** [bsorrentino/maven-confluence-plugin#109]
Hi! When using markdown for pages, all sublists renders as one single list. In attach simple realisation of sublists support. Path with adding support of sublist`s:[Path](https://gist.github.com/esivres/de91b39dd81a1f585feefe10d0e5035d)

**Comment by bsorrentino** [comment]
hi thx for contribution 

i'll integrate your patch asap

**Comment by bsorrentino** [comment]
I've deployed release ```4.10-SNAPSHOT``` with your patch

Thx again for contribution

**Comment by bsorrentino** [comment]
I've released the release `4.10`
