### ISSUE TITLE
Confluence macro syntax is getting interpreted in MD files

### ISSUE THREAD

**Issue by wattazoum** [bsorrentino/maven-confluence-plugin#111]
Hi, 

I have a MD file containing 
```
java -cp {classpaths} {mainClass} {inputPath} {outputPath} ...
```
I expected the reporting plugin to ignore those. I would understand if it where in a `.confluence`  file. But I think it's wrong in a MD file

plugin version **4.8**

**Comment by bsorrentino** [comment]
I suggest you to use 

## code block
```
    ```
    java -cp {classpaths} {mainClass} {inputPath} {outputPath}
    ```
```
##  escape

```text
    java -cp \\{classpaths} \\{mainClass} \\{inputPath} \\{outputPath}
```

**Comment by wattazoum** [comment]
My problem with this solution, is that it makes the MD file specific to confluence :-/

**Comment by bsorrentino** [comment]
not if you use code block

**Comment by wattazoum** [comment]
Here is the [original file](https://github.com/strator-dev/greenpepper/blob/upload-doc-to-confluence/greenpepper-maven-plugin/src/site/markdown/runner-ref.md) . 

if I where to escape, it would render like 
`java -cp \\{classpaths} \\{mainClass} \\{inputPath} \\{outputPath} -r \\{repository} -f \\{fixtureFactory}`

which doesn't mean the same for users.

I believe I already use `inline code`

**Comment by bsorrentino** [comment]
I've seen your doc and, in my opinion,  except for 2nd column of **includeProjectClasspath** you could use **code block** without affect the semantic of your documention

**Comment by wattazoum** [comment]
is it possible to use a code block inside a cell of a table ?

```
|  c1 |  c2 |
|---|---|
| key | value with `code` block |
```

renders

| c1 | c2 |
|---|---|
| key | value with `code` block |

How do I put **code** in a code block ?

Note: Putting my own issue aside, I think it's a bug.

**Comment by bsorrentino** [comment]
Yes agree

I'm trying to suggest a short way to solve your issue but it is not a definitively solution

Probably a good solution could be provide a configuration where we can put  a list of macros to escaping

**Comment by bsorrentino** [comment]
I've provided a fix for macro problem for the **inline** case 

so you can write 
```
my inline text `java -cp {classpaths} {mainClass} {inputPath} {outputPath}` end of inline text
```

The fix is available in version ```4.11-SNAPSHOT```

Please test it and let me know

**Comment by wattazoum** [comment]
Hi, 

I get 
```
[INFO] generateChild spacekey=[TEST] parentPageTtile=[GreenPepper Maven Plugin - References]
Page: Runner - file:/home/wattazoum/Dev/workspace/git/greenpepper/greenpepper-maven-plugin/src/site/markdown/runner-ref.md
[ERROR] error loading template
org.codehaus.swizzle.confluence.ConfluenceException: java.lang.Exception: com.atlassian.confluence.rpc.RemoteException: com.atlassian.confluence.content.render.xhtml.migration.exceptions.UnknownMacroMigrationException: The macro 'classpaths' is unknown.
        at org.codehaus.swizzle.confluence.Confluence.call(Confluence.java:971)
        at org.codehaus.swizzle.confluence.Confluence.storePage(Confluence.java:359)
        at org.bsc.maven.confluence.plugin.AbstractConfluenceMojo.generateChild(AbstractConfluenceMojo.java:287)
        at org.bsc.maven.confluence.plugin.AbstractConfluenceSiteMojo.generateChildren(AbstractConfluenceSiteMojo.java:150)
        at org.bsc.maven.confluence.plugin.AbstractConfluenceSiteMojo.generateChildren(AbstractConfluenceSiteMojo.java:154)
        at org.bsc.maven.confluence.plugin.ConfluenceDeployMojo$2.execute(ConfluenceDeployMojo.java:708)
```

**Comment by bsorrentino** [comment]
I’ve succesfully translated the page  [runner-ref.md](https://github.com/strator-dev/greenpepper/blob/upload-doc-to-confluence/greenpepper-maven-plugin/src/site/markdown/runner-ref.md)
just with few of updates

In **cmdLineTemplate** i've updated `{}` macros using inline code
