### ISSUE TITLE
[REQUEST] Render templates variables in any page

### ISSUE THREAD

**Issue by wattazoum** [bsorrentino/maven-confluence-plugin#124]
Hi, 

Currently (version 4.12) the only page in with the template variables are rendered is in the Home page. 
I would like to be able to inject each variable content in any page.

**Comment by bsorrentino** [comment]
Hi i've done a code review and just `plugin.summary` and `plugins.goals` seams missing into children

I've release version `4.13-SNAPSHOT` ... could you test it and let me know ?

Thanks in advance

**Comment by wattazoum** [comment]
Indeed, I have seen that the code seems to do it for every variable but plugins' . 
I wanted to reproduce the problem in a unit test but I couldn't.

**Comment by bsorrentino** [comment]
Could you be more precise ... as you say the code propagates variables  so: what are the variables not propagated ?

**Comment by wattazoum** [comment]
I was speaking about the code before your fix. I had noticed `plugin.goals` only.

**Comment by bsorrentino** [comment]
Ok

So I'll consider issue solved 

Thank again for your actively contribution

**Comment by wattazoum** [comment]
No problem :+1:

**Comment by bsorrentino** [comment]
fix released in `4.13`
