### ISSUE TITLE
Automatic purging of the deleted confluence pages from the space trash

### ISSUE THREAD

**Issue by amanganiello90** [bsorrentino/maven-confluence-plugin#126]
This issue is ideal because in some confluence configurations, if a page with the same name was deleted, it isn't possible to publish the same page name again (transaction-rollback exception). To resolve manually this scenario you have to purge the space trash for that page.
So a goal or a parameter plugin that executes an automatic purge before publishing is the excellent solution.

Consider the atlassian documentation related the purging: https://confluence.atlassian.com/conf56/purging-deleted-pages-658736994.html

**Comment by bsorrentino** [comment]
Hi thanks for feedback

The documentation refers to the use case from aa administrator point of view, to allow integration in plugin we need to find out something related to services (either XML-RPC or REST)

I'll search for them  ...

**Comment by bsorrentino** [comment]
Closed due inactivity.

Currently in this plugin we haven't planned administration tasks
