### ISSUE TITLE
Markdown to confluence paragraphs are formatted with "br" instead of "p"

### ISSUE THREAD

**Issue by johnmshields** [bsorrentino/maven-confluence-plugin#127]
In markdown, typically when you use two line breaks the result is a new paragraph. It seems that when exporting markdown to confluence via the plugin that both double and single newlines result in an HTML "br" instead of a new paragraph. This results in pages that look like they don't contain any real paragraphs when viewed in confluence.

Is there any background to this behavior? I'm happy to provide a PR but wanted to make sure first that there isn't something I'm missing.

Thanks!

**Comment by bsorrentino** [comment]
Hi thanks for feedback

The matter here  is translate markdown to confluence wiki so, in confluence wiki format, **paragraph** is considered an **empty line** (see [Notation Guide - text break](http://bsorrentino.github.io/maven-confluence-plugin/Notation%20Guide%20-%20Confluence.html)).

Then we have to fix issue using neither `<br>` nor `<p>` but just using **white space**
