### ISSUE TITLE
Page restrictions management

### ISSUE THREAD

**Issue by lorvell** [bsorrentino/maven-confluence-plugin#128]
It would be nice to have a way to manage page restrictions, in order to publish a page with viewing and editing permissions restricted to my reviewer, my team and so on.. before to publish to everyone. From Confluence UI i can set permission for a page and its descendents as described into doc official page:
- https://confluence.atlassian.com/doc/page-restrictions-139414.html

best regards,
Lorenzo.

**Comment by bsorrentino** [comment]
Hi 

Thanks for feedbacks

This is a interesting feature and I'll evaluate its implementation soon

**Comment by wattazoum** [comment]
Hi, 
About this feature, I have a doubt on the practical usage. Take the following scenario:

* Documentation is **Online** for users
* You update the documentation via the plugin
* Documentation is **Offline** for users
* You take 1 day to review the documentation, modify it with your team
* You open the documentation for users
* Documentation is **Online** for users

Your user will not have access to the docs from time to time, which is not well.

I suggest the following. 
- create a homepage that will be for hosting your **in development** documentation and that is protected and hidden.
- create a homepage that will be for hosting your **in production** documentation and that is accessible.

* Test your documentation and only when you are ready, publish it on the production HomePage.
