### ISSUE TITLE
Storage Format XHTML for home

### ISSUE THREAD

**Issue by hjuergens** [bsorrentino/maven-confluence-plugin#131]
The XHTML format (see [storageformat_guide](https://bsorrentino.github.io/maven-confluence-plugin/storageformat_guide.html)) seemed unsupported.
`<site>
<home uri="xhtml/mydoc.xhtml" name="pagename">
</site>`
I get the one-on-one replication of the mydoc.xhtml on the page. E.g. `<ac:link>` instead of a link.

**Comment by bsorrentino** [comment]
Hi 

Which version are you using ... ? the last one ?

**Comment by bsorrentino** [comment]
I've tested following [page](https://raw.githubusercontent.com/bsorrentino/maven-confluence-plugin/develop/maven-confluence-test/src/site/confluence/storageFormat.xhtml) against last release and all seems work well

**Comment by hjuergens** [comment]
Running into above problem with **Release 5.0-rc1** from MAVEN CENTRAL also with your example page.
Also strange: the expression `<![CDATA[got to home]]>`in storageFormat.xhtml becomes 

> <![CDATAgot to home]>

 on the confluence page, missing the inner square brackets.

**Comment by hjuergens** [comment]
Oops. Wrong button

**Comment by bsorrentino** [comment]
Which version of confluence are you using ?

**Comment by bsorrentino** [comment]
I confirm that testing [page](https://raw.githubusercontent.com/bsorrentino/maven-confluence-plugin/develop/maven-confluence-test/src/site/confluence/storageFormat.xhtml) on  confluence 5.10.0  all seems work well

> To test I use module [maven-confluence-test](https://github.com/bsorrentino/maven-confluence-plugin/tree/master/maven-confluence-test) running task ```mvn confluence-reporting:deploy@local```

**Comment by hjuergens** [comment]
Giving up on Confluence 6.0.1 (data-aui-version="5.10.1"??) while getting message
`error generating report: unexpected port: -1` using module maven-confluence-test running
task `mvn confluence-reporting:deploy@local`

**Comment by bsorrentino** [comment]
Such error looks a bit weird ... it isn't related to storage format but seems mostly related to configuration. I'll investigate on

However, about Storage Format issue,  I'll try with 6.0.1

**Comment by bsorrentino** [comment]
Seems that the problem: `error generating report: unexpected port: -1` should be related to getting **port** from **URL** parsed using given **end point** and passed to `OkHttp3.HttpUrl.Builder()`

To simplify diagnosis and fix it,  could you share your endpoint ?

**Comment by bsorrentino** [comment]
Storage Format - "error generating report: unexpected port: -1"  #133

**Comment by bsorrentino** [comment]
Can you retry using module `maven-confluence-test` running
task `mvn confluence-reporting:deploy@local` on version `5.0-SNAPSHOT` ?

Thanks in advance

**Comment by bsorrentino** [comment]
I have tested [storageFormat.xhtml](https://raw.githubusercontent.com/bsorrentino/maven-confluence-plugin/develop/maven-confluence-test/src/site/confluence/storageFormat.xhtml) page on  **confluence 6.0.1** and  all seems work well

> To test I use module [maven-confluence-test](https://github.com/bsorrentino/maven-confluence-plugin/tree/master/maven-confluence-test) running task ```mvn confluence-reporting:deploy@local```

**Comment by hjuergens** [comment]
Sorry, can't reproduce error on `maven-confluence-test`. Instead getting a 
`org.springframework.transaction.UnexpectedRollbackException: Transaction rolled back because it has been marked as rollback-only`.

My endpoints are of the form
`<endPoint>https://intranet/confluence/rpc/xmlrpc</endPoint>` or
`<endPoint>https://intranet/confluence</endPoint>`

**Comment by bsorrentino** [comment]
In my experience the error: `Transaction rolled back because it has been marked as rollback-only` is raised when there is another page in another space or in different parent that has the same title of one that you are trying to generate.

Hope this help
