### ISSUE TITLE
How Disable plugin template page to publish wiki for my custom maven plugin

### ISSUE THREAD

**Issue by amanganiello90** [bsorrentino/maven-confluence-plugin#132]
I want to use my home page wiki on my custom maven plugin. It seems that the confluence reporting plugin ignores my home page and use a default page with : 

    Index
    Description
    Plugin Goals

The configuration of the confluence reporting plugin in my pom.xml is:

``` xml
<plugin>
	<groupId>org.bsc.maven</groupId>
	<artifactId>confluence-reporting-maven-plugin</artifactId>
	<version>${confluence-reporting-maven-plugin.project.version}</version>
	<configuration>
		<endPoint>${confluence.endPoint}</endPoint>
		<spaceKey>${confluence.spaceKey}</spaceKey>
		<parentPageTitle>${confluence.parentPageTitle}</parentPageTitle>
		<title>${confluence.title}</title>
		<wikiFilesExt>.confluence</wikiFilesExt>
		<serverId>${confluence.serverId}</serverId>
	</configuration>
</plugin>
 ```
Obviously the properties declared are defined in the properties pom section.

**Comment by bsorrentino** [comment]
Hi Angelo

I need bit of more informations:

1. Which version of plugin are you using ?
2. Are you using a site definition (ie `site.xml`) ? If not ... what's the name of the file of your **"home page"** ? If yes attach it to the issue please

**Comment by amanganiello90** [comment]
Well,
1.  The maven confluence reporting plugin version is: 4.8
2.  Yes, I have a site.xml where I declare a  _<home  uri="pages/gitflow-00-toc.confluence">_ .
The home page title is in : _<title>${confluence.title}</title>_ and its value is *Oneleo-gitflow Plugin* .
Besides, this home page has children pages.

**Comment by bsorrentino** [comment]
Ok 

first at all ... you have to update version of plugin at least to `4.13` but i strongly suggest you to use  the last one (ie `5.0-rc1`) and repeat test

**Comment by amanganiello90** [comment]
Ok, with the 5.0-rc1 the issue is resolved .
