### ISSUE TITLE
Jira server targeting when multiple Jira instances integrated with one Confluence instance

### ISSUE THREAD

**Issue by apanasovich** [bsorrentino/maven-confluence-plugin#136]
The plugin adds Jira ids in the following format:
**{jira:ABSD-12345}**
Sometimes the Confluence has more than one Jira instance integrated with it, in which case it resolves the jira link by appending the first jira url prefix from the list.
There is no possibility to configure on the plugin side what Jira server should be used for the Jira links.

Suggestion is to add **jiraUrlPrefix** plugin configuration parameter and, for example, to generate the macros in a form of:
**{jira:\<jiraUrlPrefix\>/ABSD-12345}**
Or any other solution to support Jira server targeting. Thanks

**Comment by bsorrentino** [comment]
Hi, thanks for feedback 

This seems a good enhancement 

I'll working on

**Comment by yuecels** [comment]
Hey @bsorrentino is there any solution for this requirement?

**Comment by bsorrentino** [comment]
Hi @yuecels 

Jira support in this plugin is  not in active development from a while. 

What I have understood is that you need a configurable macro. 

I'll try to take a chance to give a look to understand if there is a simple solution to give you the required flexibility

**Comment by yuecels** [comment]
Hi @bsorrentino 
thank you, it would be great.

**Comment by bsorrentino** [comment]
I've moved the [Gitlog + Jira](https://github.com/bsorrentino/maven-confluence-plugin/tree/develop/gitlog%2Bjira) implementation in a new [module](https://github.com/bsorrentino/maven-confluence-plugin/tree/develop/gitlog%2Bjira) to simplify enhancement and PR
