### ISSUE TITLE
Incorrect line print in log for confluence-reporting:deploy goal 

### ISSUE THREAD

**Issue by amanganiello90** [bsorrentino/maven-confluence-plugin#138]
I want to point out a little inaccuracy. In the deploy goal it will print for a project with a parent page:

[INFO] generateChild spacekey=[PKB] parentPageTtile=[ gitflow maven Plugin - release-notes]

The error is the incorrect spelling for "parentPageTtile" instead "parentPageTitle".

The plugin version used is the 5.0-rc1

**Comment by bsorrentino** [comment]
Hi, thanks for feedback 

Yes you're right ... i'll fix it soon (probably it will be not enough for another release.. but will be part of the next one)
