### ISSUE TITLE
No single first level heading for scm section

### ISSUE THREAD

**Issue by nuvitong** [bsorrentino/maven-confluence-plugin#141]
Hi.

When using `${project.scmManager}` in site template the output contains the following first level headings (h1.):

* Overview
* Web Browser Access
* Anonymous Access
* Developer Access
* Access from Behind a Firewall

I would expect, that there is only one first level heading called e.g. "Source Code Management" and the headings above to be of second level.

What's your opinion on this?

**Comment by bsorrentino** [comment]
Hi, thanks for feedback

You right ... I'll fix this asap
