### ISSUE TITLE
How to skip plugin execution

### ISSUE THREAD

**Issue by nuvitong** [bsorrentino/maven-confluence-plugin#144]
Hi,

is there a way to skip the plugin execution? Like setting `<skip>true</skip>` in execution's configuration?

Background: in my multi module project I'd like to create the confluence site only for some of the modules. So I would configure the plugin with empty skip property within the parent module and set an according skip property within the modules, which should not deploy the site to confluence.

**Comment by bsorrentino** [comment]
Hi 

Currently there isn't skip support  (but I'll definitively plan to do it)

Meanwhile I suggest you to put in your parent the plugin definition within `<pluginManagement>` instead of `<build>`

Hope this help
