### ISSUE TITLE
skip publish of confluence pages related on submodules declared in a maven multimodule project

### ISSUE THREAD

**Issue by amanganiello90** [bsorrentino/maven-confluence-plugin#146]
I have a wiki site project under a maven multimodule project (packaging pom). So, when I publish documentation, also meta-inf pages related the maven submodules artifacts are deployed on confluence. Can I avoid to publish this pages? The version used of confluence plugin is the last (5.0). Thanks Bartolo :)

**Comment by bsorrentino** [comment]
Let me understand, do you use site descriptor or not?

**Comment by amanganiello90** [comment]
Yes, with a site.xml

**Comment by bsorrentino** [comment]
so such `meta-inf` pages are published also if them are not included in `site.xml` ?

**Comment by amanganiello90** [comment]
Yes, the page are not declared in site.xml. Now I explain you my case. I have a maven multimodule project (artifactId "custom-parent") with version 1.0-SNAPSHOT, and two submodules with artifactId "event" and "codegen". In my site I have two pages: "modelling" and "generation". Now when I publish with the confluence plugin, there are published: "modelling", "generation", "event-1.0-SNAPSHOT" and "codegen-1.0-SNAPSHOT" . The last two are paged related to jar meta inf of submodules (dependencies name, project name, pom properties etc) . This is the problem. I don't want the last two meta inf pages

**Comment by bsorrentino** [comment]
Currently the only ways to do this are:

* use `-N,--non-recursive  Do not recurse into sub-projects` maven options
* create a specific pom (without modules) for generate documentation 

I'll work on support of `skip` support
