### ISSUE TITLE
Avoid republishing for confluence pages not changed

### ISSUE THREAD

**Issue by amanganiello90** [bsorrentino/maven-confluence-plugin#150]
It's possible to publish only the confluence pages changed? I don't know if you have a sort of metadata to know the pages really changed..

**Comment by bsorrentino** [comment]
Hi

Only for attachments the plugin check the date between published and local asset

However it is an interesting feature to add. The possible implementation could be:

- Check the date between published and local page
- Generate a site's lock file that will contain the metadata for each page

**Comment by amanganiello90** [comment]
ok, I'll wait for this interesting feature :)

**Comment by bsorrentino** [comment]
Hi @amanganiello90  I've deployed the version `6.0-SNAPSHOT` with requested feature.

Could you test it and let me know ?

Thanks in advance

**Comment by amanganiello90** [comment]
Thanks, I will check it.

**Comment by amanganiello90** [comment]
Hi @bsorrentino,
I built the source code from develop to use the 6.0-SNAPSHOT version (it isn't been deployed on maven central repository http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.bsc.maven%22%20AND%20a%3A%22confluence-reporting-maven-plugin%22).
Hovewer some pages (few pages) not changed are republished from the plugin.

**Comment by bsorrentino** [comment]
Hi @amanganiello90 

The plugin generate a file named `.state.properties` could you share it 

Meanwhile i'll put more information on the log

**Comment by bsorrentino** [comment]
Hi @amanganiello90 

if you run maven with `-X` option you could see which page will be skipped 

have you a chance to share the `.state.properties` generated file

**Comment by amanganiello90** [comment]
Ok, as soon as I can, I will check

**Comment by amanganiello90** [comment]
Where is stored the __.state.properties__ file? However, both in confluence and with maven -X parameter, I see that the not changed pages are reloaded

**Comment by bsorrentino** [comment]
The file is generated in the current directory (ie where maven start) 

Please consider to use the deployed SNAPSHOT to be aligned

**Comment by amanganiello90** [comment]
I have problems to resolve with maven this snapshot version also after configuring in maven settings the sonatype repo. Besides your code is not on develop, because after a local build and running I don't see any changing of your feature for publishing wiki pages. So, could you create a branch with this feature in order to build in local and run the confluence-reporting deploy goal? Thanks

**Comment by bsorrentino** [comment]
Hi @amanganiello90 

I'm surprised that you have problem to use `SNAPSHOT`, could you try the  configuration below?

```xml
<pluginRepositories>
    <pluginRepository>
        <id>sonatype-repo</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <releases>
            <enabled>false</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </pluginRepository>
</pluginRepositories>
```

> However such implementation is on the branch **'feature/delta'**

**Comment by amanganiello90** [comment]
ok thanks, it works...but I don't find the .state.properties after publishing success :(

**Comment by amanganiello90** [comment]
ahhhh ok, I found it into src/site/confluence directory !
I suppose that in this file there are the id for every page, and the pages already published in the same deploy have the same id :)

**Comment by bsorrentino** [comment]
have you chance to join [gitter](https://gitter.im/bsorrentino/maven-confluence-plugin?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) ?

**Comment by amanganiello90** [comment]
I'm connected on gitter

**Comment by bsorrentino** [comment]
I don't see u ... please, when u ready,  join the maven-confluence-plugin room

**Comment by bsorrentino** [comment]
Implementation released in `6.0-beta1`

**Comment by qwazer** [comment]
I'm worried that some uses cases will not be covered by this approach (based on timestamps of files specified in site.xml).
For example, if change homepage title in site definition `site.xml` - content of reflinks on other pages will be changed too because rendered reflinks includes homepage title.

I want to propose a more robust approach:
store in `./target/confluence-plugin/converted_pages` internal representation of all pages  (in confluence wiki format) and attachments according site definition.
Then for every page and attachment compare it **by content**.
If content changes - publish, otherwise - not publish and print log message.

**Comment by bsorrentino** [comment]
Hi @qwazer 

This issue, raised by @amanganiello90,  was mostly to avoid re-publication during CI process.

Your suggestion is very interesting ... and I'd prefer that you'll open a new issue concerning **comparing by content**

**Comment by amanganiello90** [comment]
Great @qwazer !
