### ISSUE TITLE
How to Append data to the existing confluence page? 

### ISSUE THREAD

**Issue by devdream02** [bsorrentino/maven-confluence-plugin#151]
Hi Team,
The problem statement that i have is to publish data from multiple jenkins job to a single confluence page.
So i want to know is there a way to append the data to the existing confluence page.

Thanks in advance..!

Regards

**Comment by bsorrentino** [comment]
Hi @devdream02 

Currently plugin doesn’t support such feature but I would suggest you to find out more from confluence publishing possibilities.

For example, to handle your case, I suggest to create a *super page* with inside just *page inclusion* macros so you could generate different child pages that will be consolidated within it.

**Comment by devdream02** [comment]
Thanks for the info @bsorrentino . Page inclusion macro will work fine for me.
