### ISSUE TITLE
Could templateWiki be an URL instead of File?

### ISSUE THREAD

**Issue by Qnerd** [bsorrentino/maven-confluence-plugin#152]
I want to build an general template, which should be equal for every project.
 
My plan was to model a template.confluence file which I publish on a webserver so I can reference this in my parent pom (every project inherits from this "company wide parent pom"):
`<plugin>
	<groupId>org.bsc.maven</groupId>
	<artifactId>confluence-reporting-maven-plugin</artifactId>
	<configuration>
		<templateWiki>http://myhost:9090/template.confluence</templateWiki>
		[...]
	</configuration>
</plugin>
`

Actual this template has to be on the local filesystem, which means, that every project owner has to write his own template, which quickly leads to different documentation page structures.

So it would be nice if the templateWiki configuration could be changed in an URL object.

**Comment by bsorrentino** [comment]
Hi

I thought about your proposal and I think that is not aligned with documentation strategy  suggested by this plugin

Let me explain, firstly the documentation could be not limited by one page but more than ones, plus  attachments and this will lead to take in consideration all this complexity if we would implement your suggestion. 

Secondly if you put your template in company parent pom and publish it on public registry (e.g. sonatype, artifactory, etc .. ) you accomplish your requirement. 

Moreover if you want enforce your rules for new project I suggest  you to develop an archetype and distribute it

**Comment by Qnerd** [comment]
Hi and thanks for your quick replay.

I totally agree that a documentation is highly project individual and centralizing the template would make this very complex.

My actual use case for this plugin is to automatically generate a "project overview" (team-member, scm-informations, download links, changelogs, etc) page in confluence for every already existing projects in our company.
But I am totally okay if this is does not match with your plugin development. 

Your second point sounds interesting. I was not aware, that I can add resources (like a template.confluence) in my parent pom project. 

And as a last resort, I think forking your project and customizing it for my own individual needs looks still possible.

**Comment by bsorrentino** [comment]
You can put the global configuration of plugin in parent POM.

After that, the issue could be avoid inherit the configuration in child POM. This could be achieved in different ways:

1. add Skip on child POM configuration 
>```
><configuration>
>    <skip>true</skip>
></configuration>
>```
2. add a `report` profile in parent POM where put configuration
