### ISSUE TITLE
Replace deprecated dependency Pegdown

### ISSUE THREAD

**Issue by bsorrentino** [bsorrentino/maven-confluence-plugin#154]
The [Pegdown](https://github.com/sirthias/pegdown) project has been **DEPRECATED** so  we need a replacement.

The suggested library is [flexmark-java](https://github.com/vsch/flexmark-java)

**Comment by qwazer** [comment]
HI.
I'm interesting in this task. I want to have reusable implementation, that can be used in my project https://github.com/qwazer/markdown-confluence-gradle-plugin.
And best option is to have extension like [vsch/flexmark-java/flexmark-jira-converter](https://github.com/vsch/flexmark-java/tree/master/flexmark-jira-converter).
So my current plan:
 - [x] 1. Prepare unit test for both pegdown and flexmark implementations (done). See intermediate result here https://github.com/qwazer/maven-confluence-plugin/commits/maven-confluence-plugin-154
 - [ ] 2. Implement  flexmark ConfluenceConverterExtension
 - [ ] 3. Propose ConfluenceConverterExtension to @vsch (But confluence is out of scope of @vsch, as he said in https://github.com/vsch/flexmark-java/issues/71 so it can be no luck with this task )
- [ ] 4. Prepare PR to https://github.com/bsorrentino/maven-confluence-plugin
- [ ] 5. Implement it in my project markdown-confluence-gradle-plugin

**Comment by bsorrentino** [comment]
Hi @qwazer 

Awesome ... you'll real speed up plugin evolution .... I can't wait to see point 4

**Comment by qwazer** [comment]
Reference issue: https://github.com/vsch/flexmark-java/issues/258

**Comment by bsorrentino** [comment]
The alternative implementation has been moved to [commonmark](https://github.com/atlassian/commonmark-java)

**Comment by qwazer** [comment]
flexmark-java based and inspired by commonmark

**Comment by bsorrentino** [comment]
Hi @qwazer thanks for the feedback, I have chosen [flexmark-java](https://github.com/vsch/flexmark-java) as the first choice but I have seen that commonmark has an alter-ego in javascript and since I am developing the [confluence-site-publisher](https://github.com/bsorrentino/confluence-site-publisher) this will allow me to align the implementations.

However I've created a plugin approach ([SPI](https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html) based )for Markdown processor so it will be possible also to plug in flexmark-java implementation

**Comment by bsorrentino** [comment]
in version `6.8` has been added support of [Markdown processor](http://bsorrentino.github.io/maven-confluence-plugin/markdown_processor_guide.html) to plug new markdown implementation instead of the deprecated  **pegdown**.

We have also provided an alternative implementation based upon [commonmark](https://github.com/atlassian/commonmark-java) that is ready to use.

Currently we have choosen to keep pegdown as default implementation until next major release 7.x
