### ISSUE TITLE
Render images with relative uri as it was before PR#112 (Support referencenode)

### ISSUE THREAD

**Issue by qwazer** [bsorrentino/maven-confluence-plugin#155]
I found next problem when upgrade from 4.10 to 4.11

I want to render markdown files in several ways:
  1) by attlasian bitbucket (as github render markdown)
  2) publish to confluence
  3) by IDEA markdown plugin

If I have next code snippet from project https://raw.githubusercontent.com/devcon5io/awtt/master/documentation/src/site/markdown/images.md

```
Images
=======

Images have been generated in the `pre-site` phase from SVG.

![image.png](images/image.png)
```

before  4.10 it rendered in confluence normally, after https://github.com/bsorrentino/maven-confluence-plugin/pull/112 confluence breaks rendering.

PS I'll try to investigate more deeply and send PR if possible

**Comment by qwazer** [comment]
Looks like it not a bug

**Comment by qwazer** [comment]
#### Investigation results:

Result for converting markdown line `![image.png](images/image.png)` 
 * before 4.10 (PR https://github.com/bsorrentino/maven-confluence-plugin/pull/112): `!image.png!` |
 * after 4.10: `!images/image.png|alt="image.png"!` 

#### The problem
The problem with rendering line `!images/image.png|alt="image.png"!` in confluence is special char `/` in attachment name.
Even I will create attachment with name `images/image.png` it will not be shown by confluence due confluence restriction (also may be related https://jira.atlassian.com/browse/CONFSERVER-54912 )

#### Proposal

For relative images links with directory paths trim directory paths and keep only base filename.

For example markdown line `![image.png](images/image.png)` will be converted to `!image.png|alt="image.png"!` 

@bsorrentino If you are ok, I can prepare the PR

**Comment by qwazer** [comment]
@wattazoum You may be interested too

**Comment by wattazoum** [comment]
Hi, thank your for notifying me of this 'regression'. 

You proposal means going back to the previous behavior (pre 4.10) if I understand correctly. 
I just thought of a problem this may produce. Take the following markdown

```
# Icons Portfolio 
===========

## Twitter

![Twitter icon](twitter/icon.png)

## Slack

![Twitter icon](slack/icon.png)
```

Your proposal would display only 1 icon for both slack and twitter. I didn't test it though

**Comment by wattazoum** [comment]
Ok. I understand now.  I agree with your proposal (even though my opinion is not required for the project :-) ) .

**Comment by bsorrentino** [comment]
Hi @qwazer 

I think that for the project (as I think has stated by @wattazoum ) only the point **1** & **2** have value 

In my opinion, **for relative links**, would be better **remove its support**  and write in documentation the **guideline to avoid name conflicts**

**Comment by qwazer** [comment]
After some time I'm ok not to implement this feature. It can be so confusing for plugin users. 
Let's close
