### ISSUE TITLE
unclear doc about deployState parameter

### ISSUE THREAD

**Issue by qwazer** [bsorrentino/maven-confluence-plugin#157]
It's not clear doc

```
deployState:
Exprimental feature Deploy State Manager - Store the last deployed state If declared a local file will be generated that stores the last update of all documents involved in publication. If such file is present during every publication the plugin will check if the last update of each document has changed and skip the document if no update is detected 
```

1) typo: Exprimental -> Experimental
2) ```Store the last deployed state If declared a local file will be generated that stores the last update of all documents involved in publication.``` - too long to understand
3) I suggest to rewrite doc in terms of local cache, stored on filesystem
4) Am I true, that by default after `mvn clean` this cache will be deleted?

**Comment by bsorrentino** [comment]
Hi @qwazer 

 Yes it is true, after `mvn clean` it will be deleted.

This is the default behavior, unless the `outdir` parameter is set within ‘deployState’
