### ISSUE TITLE
Link and RefLink with title prefix implemenation

### ISSUE THREAD

**Issue by qwazer** [bsorrentino/maven-confluence-plugin#165]
I'm working on #154 and found inconsistencies in ToConfluenceSerializer behavior

Current implementation for adding title prefixes works in next manner

Input (markdown):
```
* This is my [relative](relativepage) link defined after. 
* This is my [rel] link defined after.

[rel]: relativeagain
```

Output (confluence wiki):
```
* This is my [relative|relativepage|] link defined after.
* This is my [rel|My Title Prefix - relativeagain] link defined after.
```

So `My Title Prefix -` added to RefLink in next lines of code
https://github.com/bsorrentino/maven-confluence-plugin/blob/0225e7e06ae2584f2b47f6efe8b82017de2cf0e8/maven-confluence-core/src/main/java/org/bsc/markdown/ToConfluenceSerializer.java#L611-L616

Inconsistence that for Link object title  `My Title Prefix - `is not added.

When I was think on about straightforward fix. I found that this idea is not good. 
Because [Confluence wiki](https://confluence.atlassian.com/doc/confluence-wiki-markup-251003035.html#ConfluenceWikiMarkup-Links) has special syntax for anchors, space keys, blogposts, etc. Implementation will be complex and buggy.

So I have other idea:
To write `ConfluenceWikiLinkResolver implements LinkResolver` in other way and add new feature:

Feature is
 specify links between markdown files as relative links in file system.
For example:
two files, **1.md** and **2.md** in a same directory,  where 1.md refer to 2.md in next way 
**1.md:**
```
[2](2.md)
```

2.md has `Title 2` in Confluence Site Description site.xml

So result of converting to Confluence Wiki should be:

1.confluence:
```
[2|Title 2]
```

Where `Title 2` - title of page in Confluence.

@bsorrentino, What do you think if I'll try to implement such `ConfluenceWikiLinkResolver`, contribute it to flexmark project and use in your project.

Drawback - backward compatibility for links with title replacement will not be saved when migrate from PegDown to FlexMark.

**Comment by qwazer** [comment]
And FYI, my current work (dirty and mostly experimental) resides here https://github.com/qwazer/flexmark-java/tree/flexmark-confluence-wiki-converter

**Comment by bsorrentino** [comment]
@qwazer I'll take a look in deep in the next days ... so that I'll better answer to your  question

thanks for your effort

**Comment by bsorrentino** [comment]
from release `6.x` issue has been solved
