### ISSUE TITLE
Improvement for node cli

### ISSUE THREAD

**Issue by amanganiello90** [bsorrentino/maven-confluence-plugin#172]
Great project, I'm studying also reactive programming for my projects with this usefull implementation of the maven confluence plugin. But in my opinion, it would be nice to have a package.json with the typescript cli ( I suppose that you transpile the files under _ts_ folder in _dist_ with the *tsc* command), a npm script to perform this, and finally a .npmignore in order to publish only the dist folder without ts files. All these things could be automated in ci with a .travis file for your *cli* branch (I guess that the *cli-dev* branch is the development branch while the *cli* branch contains your releases).

If you want, I can help you and open a pull request for the code review.
It is a suggestion :).
Thanks

**Comment by bsorrentino** [comment]
Hi @amanganiello90 

It would be great ... go ahead with PR

**Comment by amanganiello90** [comment]
Thanks, Bartolo! I integrated the typescrypt cli in the package.json, but I have errors when I transpiles the files (maybe for tsconfig.js configuration or typescript version). Could you give me your typescrypt cli version and/or the commands that you performs to generate **js** file under dist?

**Comment by bsorrentino** [comment]
I use only `tsc --watch` during development

```
> tsc --version
> Version 3.0.1
```

**Comment by amanganiello90** [comment]
Don't you install typings? I have ts error during transpilation. For example:

```
ts/logo.ts:45:15 - error TS2345: Argument of type '<T>(array: ArrayLike<T>, scheduler?: IScheduler) => Observable<T>' is not assignable to parameter of type '_ValueOrSelector<string[], ArrayLike<{}>>'.
  Type '<T>(array: ArrayLike<T>, scheduler?: IScheduler) => Observable<T>' is not assignable to type '_Selector<string[], ArrayLike<{}>>'.
    Types of parameters 'scheduler' and 'index' are incompatible.
      Type 'number' is not assignable to type 'IScheduler'.

45     .flatMap( Rx.Observable.fromArray )
```

**Comment by amanganiello90** [comment]
I resolved the errors...You have only to link your repo to travis and define the NPM_TOKEN (in travis buid plan) variable of **travis.yml** file to use the npm publish in the continuous integration. I Add the PR https://github.com/bsorrentino/maven-confluence-plugin/pull/174. If you are happy, please insert me as contributor :)
