### ISSUE TITLE
Jira issues "Error in the JQL Query"

### ISSUE THREAD

**Issue by jnie** [bsorrentino/maven-confluence-plugin#175]
Since the ${gitlog.jiraIssues} is adding links to our Jira system I get this error:

"Error in the JQL Query: Expecting operator before the end of the query. The valid operators are '=', '!=', '<', '>', '<=', '>=', '~', '!~', 'IN', 'NOT IN', 'IS' and 'IS NOT'."

Apparently because the JQL is only adding the jira issue number, f.ex "ABC2SD-1623" in the link:
"https://jira.server.com/issues/?jql=ABC2SD-1623" and it should have been "https://jira.server.com/browse/ABC2SD-1623"

Any chance to configure this behavior?

**Comment by qwazer** [comment]
Try to include macros {jira:KEY-123} in a page in your Confluence instance.
Will it be rendered correctly?

${gitlog.jiraIssues} inserts a list of wiki macros like

```
{jira:KEY-123}
{jira:KEY-124}
```

org.bsc.maven.reporting.renderer.GitLogJiraIssuesRenderer#formatJiraIssuesToString in https://github.com/bsorrentino/maven-confluence-plugin/blob/master/maven-confluence-reporting-plugin/src/main/java/org/bsc/maven/reporting/renderer/GitLogJiraIssuesRenderer.java#L47

**Comment by jnie** [comment]
@qwazer I tried your suggestion, and it actually does not render correctly either.
Would that happen to be a faulty setup of our confluence connection to Jira?

Thnx for answering :)

**Comment by qwazer** [comment]
I don't know. see errors in confluence log and try to search in google or ask Atlassian support.

**Comment by qwazer** [comment]
@jnie @bsorrentino  I believe, this issue can be closed

**Comment by yuecels** [comment]
Hey @jnie do u find any solution for this problem?

**Comment by jnie** [comment]
Hey @yuecels  no I did not, I ended up abandoning the possibility to add this to confluence.

**Comment by yuecels** [comment]
Hey @jnie thanks for the information.
