### ISSUE TITLE
Optimize Confluence interaction

### ISSUE THREAD

**Issue by qwazer** [bsorrentino/maven-confluence-plugin#176]
Optimize Confluence Client in the plugin.

1) reuse authorization session. 
2) add debug output to see request/responses 

Our production confluence has very slow authorization mechanism due to some security and technical reasons. Usage of this plugin becomes problematic, because too many auth request used. It's better to reuse HTTP session of authorized user to optimize performance.

**Comment by bsorrentino** [comment]
Hi @qwazer are you referring to **xmlrpc** protocol ?

**Comment by qwazer** [comment]
No, REST API

**Comment by bsorrentino** [comment]
Currently i use `basic auth` i don't know yet if is it possible use different authc model ( eg token) available

**Comment by bsorrentino** [comment]
As states in Q&A [Confluence REST API token authentication](https://community.atlassian.com/t5/Confluence-questions/Confluence-REST-API-token-authentication/qaq-p/611790), currently seems that, the only way to authenticate REST APi is the `basic authc`

Protocol `XMLRPC` supports token, so I'll work on it ... the only chance you have is to switch protocol after I've terminated improvement
