### ISSUE TITLE
Warn about trailing space in page names

### ISSUE THREAD

**Issue by qwazer** [bsorrentino/maven-confluence-plugin#182]
Use case:

In site description I accidentally add space to the name of page

```xml
 <home name="Name A  "
```

Confluence has page with title `Name A`

When publish with Maven Confluence plugin it accept title `"Name A  "` and try to create new page.
But Confluence report error that page with this title already exists.

It will be nice to validate site description for trailing names or either
1) report error and don't try to publish errors
2) trim titles with warning messages in log

I prefer the 1 option.

**Comment by bsorrentino** [comment]
Hi @qwazer 

Agree with you .... i’m Going to implement option 1

**Comment by bsorrentino** [comment]
fix released in `6.0-rc4`

**Comment by qwazer** [comment]
Thanks!
