### ISSUE TITLE
Image Markdown does not work correctly

### ISSUE THREAD

**Issue by Prideth** [bsorrentino/maven-confluence-plugin#187]
when using confluence-plugin together with maven-pdf plugin.

this syntax should work like documented:
`
1= 
![Alt-Text2](./images/logos/image.jpg "text")
`

`
2=
![Auswahl.png](./images/Beispiele/Auswahl.png) !Auswahl.png! 
`

if I use 1) . pdf works, but confluence only says "Unknown Attachment"

if I use 2) . I got both "Unknown Attachment" and the picture in confluence and picture and a text with `!Auswahl.png!` in pdf. 

Both is not really nice.

`
<child name="test" uri="../markdown/Beispiele/test/Variante.md">
				<attachment name="Auswahl.png" uri="../resources/images/Beispiele/test/Auswahl.png" contentType="image/png" comment="kommentar" ></attachment>
			</child>
`

**Comment by Prideth** [comment]
`![${pageTitle}^image-name.png](.images/image-name.png "")` like in the docu, does not work either

**Comment by bsorrentino** [comment]
Hi @Prideth 

Let me verify because syntax `![${pageTitle}^image-name.png](.images/image-name.png "")` should work. 

Which version of plugin are you using ?

**Comment by Prideth** [comment]
I use the 6.2. Here my example:




![grafik](https://user-images.githubusercontent.com/3940132/54664096-86234200-4ae3-11e9-9f9f-13e310f5bf3c.png)


`![${pageTitle}^coffee171653.jpg](.images/coffee171653.jpg "")`

`
<child name="Markdown" uri="../markdown/markup.md">
        
        	<attachment name="coffee171653.jpg" uri="../resources/images/coffee171653.jpg" contentType="image/jpg" comment="kommentar" ></attachment>
`

`
<plugin>
		            <groupId>org.bsc.maven</groupId>
		            <artifactId>confluence-reporting-maven-plugin</artifactId>
		            <version>6.2</version>
		        </plugin>
`

**Comment by bsorrentino** [comment]
Hi @Prideth 

I've tested, using your information and the problem is that documentation wrongly describe the way to declare image in markdown 

`![${pageTitle}^coffee171653.jpg](.images/coffee171653.jpg "")` **IS WRONG**!

## Solutions

* `![.images/coffee171653.jpg ](${pageTitle}^coffee171653.jpg "")`
* `![](${pageTitle}^coffee171653.jpg "")`

Please test and let me know

**Comment by Prideth** [comment]
does not work. 

works for confluence: 
![./images/Beispiele/Move/Auswahl-Ecore-Datei.png](Auswahl-Ecore-Datei.png "")

works for pdf or else:
![Auswahl-Ecore-Datei.png](./images/Beispiele/Move/Auswahl-Ecore-Datei.png "")

Nothing that works for both.
Do you have an idea what to do?
