### ISSUE TITLE
Include Project Reports (generated reports)

### ISSUE THREAD

**Issue by capeflynn** [bsorrentino/maven-confluence-plugin#190]
Is it possible to upload the Project Reports section with the site for generated reports such as for Javadocs? If not I think this would be a very useful enhancement.

![site-javadocs](https://user-images.githubusercontent.com/50003041/60122396-1dd3a480-9753-11e9-9e2b-9de7d052daf6.png)

**Comment by bsorrentino** [comment]
hi @capeflynn 

At beginning I've ignored javadoc because was not possible deploy javadoc itself on confluence. For this reason seems to me useless such feature. 

What do you think about ?

**Comment by capeflynn** [comment]
Hi @bsorrentino 

Thank you very much for the quick response!

I'm looking for ways to pull documentation from code and automatically deploy it to a central location, such as Confluence, during the release process. We currently use Maven and Confluence so I was looking in these areas, but am open to alternative solutions.

The project information created during the `mvn site` is good information, but it does not really help developers better understand the code or how to support it. Javadocs was the first place I thought of that could be autogenerated from code. I believe there has been some people working on converting it into XHTML or Markdown which seems to lend itself to being deployed to multiple places such as Confluence or Github/Bitbucket.

Maybe I'm off base, but your work seems to be the closest to my ideal solution.

**Comment by bsorrentino** [comment]
Hi @capeflynn 

Idea behind the plugin is to develop a documentation tailored to your needs. To achieve this, I suggest you not using `site` goal  ... but rather `confluence-reporting:deploy`

**Comment by qwazer** [comment]
@capeflynn IMHO it's better to keep and publish javadocs artifacts to maven repo. There some solutions like Artifactory, that have "Content Browsing"  feature. This allows browsing with web-browser javadocs published as maven artifacts from jars.Just use URL like "http://repo/cooridnates_of_maven_artifact/..javadoc.jar!/index.html"

**Comment by bsorrentino** [comment]
Sure ... but we have to separate concerns.

This plugin allow to publish documentation to confluence (not exclusively the `site` generated one).
Yo can use confluence wiki or markdown to create link to whatever resource coming out from whatever place 

The limit is your imagination

**Comment by capeflynn** [comment]
@qwazer -- thank you for the suggestion, that is a good idea.

@bsorrentino -- I am using the `confluence-reporting:deploy` plugin, instead of the `site` plugin, but I would like to upload the autogenerated `reporting-info` to confluence too, but I get an error message when I try to upload that information.

Maybe the best solution is what **qwazer** mentioned and upload the site with the artifacts to the Nexus repo. The only draw back is having documentation in two different locations and the look and feel is not as nice as a wiki page. I really liked the idea of all the documentation being centrally located in one place.

If this plugin can publish all documentation to confluence, how would I use it to publish auto-generated documentation to confluence?

**Comment by bsorrentino** [comment]
@capeflynn 

Please provide me more context:

 * Are you generating doc for Plugin or for a Project ?
 * For _reporting-info_ do you mean the html file generated by standard maven site ?

**FYI**: Currently the plugin use the [Template Variable Concept](http://bsorrentino.github.io/maven-confluence-plugin/usage.html) to map in confluence wiki the standard maven site info.
> Probably you need other **template variables** is it so ?

**Comment by capeflynn** [comment]
@bsorrentino 

You are absolutely right, sorry for the confusion.

- I am generating documentation for a Project.
- Yes, I am referring to the HTML files created from the standard `mvn site`

I have used the templates with the `confluence-reporting` plugin with some of the variables, but could not find variables to include reports generated during build, such as javadocs. It seems like more template variables would be very helpful.

**Comment by bsorrentino** [comment]
Well, I'll start to working on

**Comment by capeflynn** [comment]
wow @bsorrentino that is great, thank you very much! Let me know if there is something I can do to help.

**Comment by bsorrentino** [comment]
Hi @capeflynn 

your feature request seems quite complex because to build project reports, are directly involved maven plugins (eg. javadoc, PMD, etc ) that contribute.

This mean that I've to replicate the maven-site behaviour to implement it.

**Comment by capeflynn** [comment]
Hi bsorrentino,

Sorry to hear it has been giving you such trouble. I wouldn't think you
want to rebuild a plugin that exists already. Too bad there wasn't a way to
just fork that project and add your functionality to the maven site plugin.

I really appreciate your help and looking into this functionality.

**Comment by bsorrentino** [comment]
Hi @capeflynn 

No problem. I love to implement new functionalities.. just in this case the implementation seems too complex.

However I suggest you to create a custom confluence page that just contains the links of generated reports

**Comment by capeflynn** [comment]
I agree with your solution. I'm going to look into a Nexus site repository
and link to that from Confluence. I'm hoping to use the template
functionality in your plugin so the pages can still be dynamically created.
It is not exactly what I had in mind, but it does keep the artifacts and
Java Docs closer, so that might end up being a good thing. Thank you very
much for your help looking into this functionality.

**Comment by bsorrentino** [comment]
Hi @capeflynn, glad to read that my suggestion could be feasible for you.

Keep in mind that whatever feedbacks is always welcome
