### ISSUE TITLE
Improve debug logging to view generated ID of attachments

### ISSUE THREAD

**Issue by qwazer** [bsorrentino/maven-confluence-plugin#192]
HI @bsorrentino 

Could you please improve debug logging in your confluence client to view ID of generated or updated attachment.

I'm found a strange execution in  6.3.2 and in 6.0-rc4.
I have a list of attachments and sometimes plugin logs messages from method
org.bsc.maven.confluence.plugin.AbstractConfluenceSiteMojo#generateAttachment
but the attachment does not appear in Confluence.

I think this is a race because when I debug I cannot reproduce it. 
The requested logging will help to identify the issue.

**Comment by bsorrentino** [comment]
hi @qwazer 

I'll do asap

**Comment by bsorrentino** [comment]
Hi @qwazer 

I've deployed develop release `6.3.3-SNAPSHOT` improving debug on attachment

Please try it and let me know if it works as expected ( obviously use `-e` or `-X` maven option )

**Comment by bsorrentino** [comment]
Hi @qwazer any news?

I'm gonna merge and close issue

**Comment by qwazer** [comment]
HI @bsorrentino 
Thanks a lot. It's really nice logging in the new SNAPSHOT version.
I cannot reproduce the issue with attachment creation. Anyway, let's merge the improved logging. I will watch for issue in the next few weeks.
