### ISSUE TITLE
Add Scroll Versions for Confluence plugin support

### ISSUE THREAD

**Issue by neko-gg** [bsorrentino/maven-confluence-plugin#194]
Ciao Bartolo,

[Scroll Versions for Confluence](https://marketplace.atlassian.com/apps/1210818/scroll-versions-for-confluence) is a Confluence plugin by [K15t](https://help.k15t.com/scroll-versions/latest/scroll-versions-110528202.html) with 1500+ users that can be used, among other things, to author and release multiple versions of Confluence pages in a single space.

It organizes page versions using [ad-hoc page names](https://help.k15t.com/scroll-versions/latest/link-to-pages-in-a-versioned-space-153653456.html), differentiating between a master page (the old school Confluence page), and multiple dot pages (one for each version).

This plugin offers both [Java APIs](https://help.k15t.com/scroll-versions/latest/use-the-java-api-162693512.html) and [REST APIs](https://help.k15t.com/scroll-versions/latest/use-the-rest-api-162693639.html) (even though the latter are not officially supported).

The REST APIs resources and how to manage page versions are [documented here](https://help.k15t.com/scroll-versions/latest/api-resources-164037049.html).

In my specific case, I'm running Confluence 6.13.4 with Scroll Versions for Confluence 3.14, and when using maven-confluence-plugin 6.4 my pages are published as "unversioned". I would like to publish versioned pages, it there any way to do it?

Since maven-confluence-plugin already supports the standard Confluence REST APIs, do you think the benefit of adding support for Scroll Versions REST APIs is worth the risk associated with them not being officially supported?

Or are Scroll Versions Java APIs easy enough to integrate in maven-confluence-plugin?

Thank you

**Comment by bsorrentino** [comment]
Hi @neko-gg 

The pages versioning in confluence  is a hot-topic.  I personally love simpler solutions so I suggest to put version in page name.

However I'll take a look to this custom solution in oder to understand if its integration does't imply drammatic change to the current implementation 

I'll let you know asap (watch project to keeep you informed)

**Comment by neko-gg** [comment]
Hi @bsorrentino,

just to keep you updated, I tried to implement a custom `ConfluenceService` to integrate Scroll Versions features via REST APIs. I delegated via composition most of the functionality to `RESTConfluenceServiceImpl`, and handled transformations from master pages to/from dot pages where needed.

Here's the diff:
https://github.com/bsorrentino/maven-confluence-plugin/compare/develop...neko-gg:feature/scroll-versions-integration

Changes to the current codebase look minimal (actually, I only modified integration test classes to reuse your test cases).

Anyway, I only touched the core, so Maven plugin configurations and `ConfluenceService` factory still need to be adapted.

If you want to run the integration tests as they are now, you'll need a `TESTSV` space with Scroll Versions `ALPHA` and `BETA`, and a versioned `Home` page.

If you feel like I'm on the right path and this integration is not too invasive, let me know if you think I can help you out somehow.

**Comment by bsorrentino** [comment]
Hi @neko-gg 

Your core  implementation looks amazing (i would like just be sure that scroll versions integration is coded a pluggable addon) ... please arrange a PR asap.

**Comment by neko-gg** [comment]
Hi @bsorrentino,
sorry for the delay. Glad you like it! :)

I created PR #197

**Comment by bsorrentino** [comment]
fix deployed in version `6.5-beta1`
