### ISSUE TITLE
Two JUnit tests fail on Windows for path issues

### ISSUE THREAD

**Issue by neko-gg** [bsorrentino/maven-confluence-plugin#195]
Hi @bsorrentino,

when running `mvn test` on Windows, two JUnit tests fail for path-related problems.

1. `SiteLoadTest#testLoadFromYAML`
```java
java.lang.AssertionError: 
Expected :<file:///C:/tmp/encoding.confluence>
Actual   :<file:/C:/encoding.confluence>

at org.bsc.confluence.model.SiteLoadTest.lambda$testLoadFromYAML$1(SiteLoadTest.java:60)
```
this is because `"/tmp"` is not considered a directory on Windows systems but a file (`Files#isDirectory` returns `false`), and so `Site#setBasedir` doesn't correctly set the `_basedir` field.
This can be easily solved by delegating `Files` to create a temp directory with `Files.createTempDirectory`.

2. `ConfluenceUtilsTest#pathTest`
```java
java.nio.file.InvalidPathException: Illegal char <:> at index 4: http://test.xml

at org.bsc.confluence.ConfluenceUtilsTest.pathTest(ConfluenceUtilsTest.java:28)
```
but the second `Paths#get` fails too.
I don't really get the meaning of this test: what is actually being tested here?

**Comment by neko-gg** [comment]
I have opened a pull request (#196) to use `Files#createTempDirectory` instead of `"/tmp"`, and `@Ignore` test `ConfluenceUtilsTest#pathTest`.
If you can help me understand what `ConfluenceUtilsTest#pathTest` is supposed to do, I can try to make it work on Windows too.

**Comment by bsorrentino** [comment]
Hi @neko-gg thanks for the contribution I've merged the PR into develop
