### ISSUE TITLE
Add possibility to use markup in the site definition

### ISSUE THREAD

**Issue by LZaruba** [bsorrentino/maven-confluence-plugin#202]
Currently, the site definition is loaded, as is without processing. Adding a markup (freemarker, for example) would allow the construction of dynamic site definitions. 

It would enable more extensive projects to define rules for attachments, child pages, etc. in the parent pom. These would then evaluate the proper result in the child project.

I'll prepare the PR.

**Comment by bsorrentino** [comment]
Hi @LZaruba 

This is a great idea and thanks for your PR,  however, starting from this idea, I would implement possibilty to plug different "template engine" and not force to use one.

So I'll think about how to implement it

**Comment by bsorrentino** [comment]
fix released in [6.7](https://github.com/bsorrentino/maven-confluence-plugin/releases/tag/v6.7) version
