### ISSUE TITLE
Replace invalid characters in labels

### ISSUE THREAD

**Issue by LZaruba** [bsorrentino/maven-confluence-plugin#204]
Currently, there is no sanitation of labels, and using an illegal character in the label will cause the failure of the goal. Add sanitation of label values replacing invalid characters.

https://jira.atlassian.com/browse/CONFSERVER-7934

**Comment by bsorrentino** [comment]
fix available from release [6.6](https://github.com/bsorrentino/maven-confluence-plugin/releases/tag/v6.6)
