### ISSUE TITLE
Add possibility to disable url properties resolving

### ISSUE THREAD

**Issue by LZaruba** [bsorrentino/maven-confluence-plugin#206]
Currently, if any property is parsable to java URI and its scheme is not null, it will be resolved (data from URL will be downloaded and will be used as the variable value). This behavior might be undesirable with some properties.

Add a configuration option that will disable this behavior.

**Comment by bsorrentino** [comment]
fix available from release [6.6](https://github.com/bsorrentino/maven-confluence-plugin/releases/tag/v6.6)
