### ISSUE TITLE
Problem with big ID of a parent page

### ISSUE THREAD

**Issue by nikolkax** [bsorrentino/maven-confluence-plugin#213]
Hello, I have a problem. My parent page has id more than integer max size, and I get an Exception: java.lang.NumberFormatException: For input string: "2182288832". The problem is in RESTConfluenceServiceImpl.createPage(Model.Page parentPage, String title) when it invoks Integer.valueOf(id). I think better solution is change signature of jsonForCreatingPage from (String, int, String) to (String, String, String). Help me please and release a new version of the plugin.

**Comment by bsorrentino** [comment]
hi @nikolkax, I'll verify and provide fix asap

**Comment by bsorrentino** [comment]
I've released version `6.7.3` with fix
