### ISSUE TITLE
Can't create a blogpost

### ISSUE THREAD

**Issue by sebb840** [bsorrentino/maven-confluence-plugin#219]
Hi,

Is it possible to create a blogpost which is like a create page ? The functionnality require only the type=blogpost insteadof page.
I think it's a good idea to offer a parameter type in the pom.xml with differrent value blogpost, page, ...
The rest api url structure seems to be equivalent.

Thanks

**Comment by bsorrentino** [comment]
hi @sebb840 

This is a good idea. I'll take it in consideration in the next versions

**Comment by bsorrentino** [comment]
Hi @sebb840 

I've done an assessment of your request.

Seems to me that `blogpost` is a single page (i.e. no children ) with labels and attachments. If is it so, to keep the consistency of the plugin publication model,  I think that we have to extend the model itself with a new entity `blogpost` enforcing that rules.

I expect as outcome of this new feature that in the Site Model we will have other than `home`, `page`, `attachment`, `label` also `blogpost`.   

what do you think about?

Thanks in advance

**Comment by sebb840** [comment]
Hi,

If Blogspot and page are different then it's a ggod idea to extends it as a new model.
What do you mean by "Site Model"  ? Are you talking about the templates ?

**Comment by bsorrentino** [comment]
Hi @sebb840 

thanks for feedback

as site model I mean [Site definition](http://bsorrentino.github.io/maven-confluence-plugin/site_xml_guide.html) 

If you agreed on that I'll proceed, let me know

Thanks in advance

**Comment by sebb840** [comment]
Hi,

I agree with you.

Thanks

**Comment by bsorrentino** [comment]
I've decided to create a new mojo goal named `blogpost` I've finalized implementation and a development preview is in `6.9-SNAPSHOT` releaase

**Comment by bsorrentino** [comment]
feature added to release `6.9-rc1`
