### ISSUE TITLE
CommonMark-Problem: Line after list is indented

### ISSUE THREAD

**Issue by jfabianmeier** [bsorrentino/maven-confluence-plugin#228]
First of all: Thanks for the effort and the great tool!

# My problem

When I use something like this in markdown:

````
- Dog
- Cat

Hen
````
Then the line "Hen" is indented as if it were part of the list. This happens when using the CommonMark engine.

Writing something like

````
- Dog
- Cat

Bird

Hen
````
only the "Bird" is indented, not the "Hen".

So somehow the next line or next block is considered to be part of the list. 

This happens with every list.

Any idea?

**Comment by bsorrentino** [comment]
Hi @jfabianmeier thanks for feedback

I faced with the same problem take a look my answer [here](https://github.com/bsorrentino/maven-confluence-plugin/issues/226#issuecomment-694833053)

hope this help

**Comment by bsorrentino** [comment]
Hi @jfabianmeier 

I close issue due inactivity. I assume that the answer has been accepted
