### ISSUE TITLE
Add Issue Tracking build in report

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bsorrentino/maven-confluence-plugin#24]
```
add a new built-in template variable ${project.issues} to generate Issue 
Tracking report
```

Original issue reported on code.google.com by `bartolom...@gmail.com` on 6 Oct 2011 at 1:48

**Comment by qwazer** [comment]
related to https://github.com/bsorrentino/maven-confluence-plugin/pull/76

**Comment by bsorrentino** [comment]
consider use of use `${gitlog.jiraIssues}` instead of `${project.issues}`
