### ISSUE TITLE
add i18n titles to ProjectSummaryRenderer and ScmRenderer

### ISSUE THREAD

**Issue by 3a04huk** [bsorrentino/maven-confluence-plugin#242]
as is:
on [scm](https://github.com/bsorrentino/maven-confluence-plugin/blob/e1b39e61f309fffd824478804af69dd280a88c1d/plugin-reporting/src/main/java/org/bsc/reporting/renderer/ScmRenderer.java#L120) and [project summary](https://github.com/bsorrentino/maven-confluence-plugin/blob/e1b39e61f309fffd824478804af69dd280a88c1d/plugin-reporting/src/main/java/org/bsc/reporting/renderer/ProjectSummaryRenderer.java#L38) titles used hardcoded strings
**ProjectSummaryRenderer** `	public String getTitle() {
		return "Project Summary";
	}`

**ScmRenderer:**  `startSection( "Source Control Management");`

to be:
**ProjectSummaryRenderer**  `	@Override
	public String getTitle() {
        return getReportString( "report.summary.title" );
	}`

**ScmRenderer:**  `startSection( getI18nString("title"));`

**Comment by bsorrentino** [comment]
Hi @3a04huk thanks for feedback 

I'll work on asap

**Comment by bsorrentino** [comment]
fix released in `7.0-beta2`
