### ISSUE TITLE
Problem when publishing pages with same name

### ISSUE THREAD

**Issue by TCke83** [bsorrentino/maven-confluence-plugin#246]
I'm using the plugin to publish content to confluence, but i see strange behaviour.

I've set the **parentPageId** but it seems to be ignored when there is another page on the space with exact the same name.

e.g. I post a page named **Foo** with a child page **Bar**. When there is a page already existing with the name **Foo** in another place on the space it gets overwritten with the new page and the child page is moved under that page, that doesn't have any relation with the parentPageId supplied to generate the documentation.

My maven config is as following:

```xml
<plugin>
    <groupId>org.bsc.maven</groupId>
    <artifactId>confluence-reporting-maven-plugin</artifactId>
    <version>7.0-rc1</version>
    <configuration>
        <childrenFolder>pages</childrenFolder>
        <endPoint>https://****/rest/api</endPoint>
        <failOnError>true</failOnError>
        <parentPageId>${confluence-reporting-maven-plugin.parentPageId}</parentPageId>
        <serverId>confluence</serverId>
        <siteDescriptor>${basedir}/target/site/confluence/site.xml</siteDescriptor>
    </configuration>
</plugin>
```

My site.xml has the following config:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bsc:site
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xmlns:bsc='https://github.com/bsorrentino/maven-confluence-plugin'
        xsi:schemaLocation='https://github.com/bsorrentino/maven-confluence-plugin https://raw.githubusercontent.com/bsorrentino/maven-confluence-plugin/master/schemas/site-schema-6.0.xsd'>
    <home name="Foo" uri="foo.md">
        <child name="Bar" uri="pages/bar.md"/>
    </home>
</bsc:site>
```

**Comment by bsorrentino** [comment]
Hi @TCke83 I'm bit confused because for what is my experience in Confluence usage I know that is not possible to have two o more page with the same name in a space.

So probably what you call "strange behaviour" is the right one

**Comment by TCke83** [comment]
Hi @bsorrentino thanks for the clarification, i didn't know there was such a kind of restriction on Confluence. I tried making a page manually with the same name and indeed it doesn't allow it to be created because the name already exists.

Thanks for the quick reply!
