### ISSUE TITLE
Problem with markdown 'lists' in confluence page generation

### ISSUE THREAD

**Issue by bsorrentino** [bsorrentino/maven-confluence-plugin#255]
### Discussed in https://github.com/bsorrentino/maven-confluence-plugin/discussions/247

<div type='discussions-op-text'>

<sup>Originally posted by **TCke83** March 22, 2021</sup>
If I use lists in my *.md files it seems to generate wrong formatting in confluence:

example

`# heading`
`* list item 1`
`* list item 2`
`# heading 2`

When this is generated, the confluence page adds the heading to the list, even if I add extra empty lines between the list and the second heading it keeps adding the second heading to the list. Is there a way to stop the list?</div>

**Comment by bsorrentino** [comment]
I've deployed release `7.3-SNAPSHOT` with a candidate solution

**Comment by nagper** [comment]
Tested, works perfectly for me!
Thanks!
