### ISSUE TITLE
Bad Formatting of Confluence Wiki page

### ISSUE THREAD

**Issue by sorrentinov** [bsorrentino/maven-confluence-plugin#262]
Hi,

I tried to deploy a simple site with standard Confluence Wiki formatting:
```
h1. I'm the first Child

*bold text*

_italics_	

??citation??	

-deleted-
	
+inserted+
```

After deploy the page in Confluence I see this result that not contains the right formatting on "citation", "strikethrough" and "underline" fragment:

![confluence_test_page](https://user-images.githubusercontent.com/4456300/149774874-3132ee15-a596-4f62-b5cb-bdfde92d7cef.png)

The strange thing is that if I export the page in PDF or view the history of page I see the correct format
I tried also to clear cache in the browser but the result is the same

I'm using **Confluence 7.15 (Latest)**

**Comment by bsorrentino** [comment]
Hi @sorrentinov thanks for feedback

I tried on confluence server 7.15 and all seems work well

are you using confluence server or confluence cloud ?

**Comment by sorrentinov** [comment]
I'm using Confluence Cloud 7.15

**Comment by bsorrentino** [comment]
Hi @sorrentinov I've tested publishing on * confluence cloud 7.15 * and the behavior has been the same that you pointed out.

Take a note that seems that only `?? citation ??`, `-deleted-`, `+ inserted +` not work properly in my overall wiki tests.

For this reason my guess is that probably there is a bug on rendering from confluence side, so I'm considering to open an issue on Atlassian support
