### ISSUE TITLE
Problem parsing % character as plain text

### ISSUE THREAD

**Issue by sebastianaguerre** [bsorrentino/maven-confluence-plugin#282]
Hi, I've been using this awesome plugin but I found that there are some issues when a % symbol is written onto the .md file as plain text

Let me show a couple of examples

> ... test coverage of at least 70%. (Measures to show this for each PR will need to be investigated)

Threw this error
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/115018868/209106636-a21f2825-6c9d-42ff-90c1-5687a623d2fb.png">

And had to be changed to 

> ... test coverage of at least 70 percent (Measures to show this for each PR will need to be investigated)

Another example (with the url changed - in bold the part that stays the same and has the problem)

> For that, first you need to configure kubectl like described here: https://mypage.com/folder/anotherfolder/**guides_%26_docs**/yetanotherfolder

Threw this error

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/115018868/209108501-bf244114-d25f-42ac-b7e5-5a9f77c20765.png">

And had to be changed to be shown as a link to work

> For that, first you need to configure kubectl like described here [DOCUMENTATION](https://mypage.com/folder/anotherfolder/**guides_%26_docs**/yetanotherfolder)

While this kind of error requires a workaround that is not that terrible to do, the main issue at least for me was to actually understand what was going on. I think it worth checking if there's something that can be done for this.

**Comment by bsorrentino** [comment]
Hi @sebastianaguerre  

Thanks to use such plugin and for your valuable feedbacks.  I'll check asap

**Comment by bsorrentino** [comment]
Hi @sebastianaguerre 

I've find out the problem. during markdown parsing has been used `String.format()` and then `%` is marked as special char.

Currently you can add another `%` as workaround

```
test coverage of at least 70%%. (Measures to show this for each PR will need to be investigated)
```

**Comment by bsorrentino** [comment]
Hi @sebastianaguerre 

I've deployed version `7.9-SNAPSHOT` with the fix. Please take a chance to test it so I can arrange a new production release

**Comment by Elisedlund-ericsson** [comment]
Also ran into this exact issue. Nice seeing it already being solved.

There's is an issue with 7.9 not being available however:
https://search.maven.org/artifact/org.bsc.maven/confluence-reporting-maven-plugin
https://mvnrepository.com/artifact/org.bsc.maven/confluence-reporting-maven-plugin

Strangely enough I was able to fetch 7.9-SNAPSHOT and can confirm that the fix  solves the issue with "%" in md files. (also figured out the "%%" workaround)

I would like however to use 7.9 and not  7.9-SNAPSHOT or 7.8+%% workaround so please lookinto the issue with 7.9 not being available
