### ISSUE TITLE
7.9 seems to not have been properly released public repositories

### ISSUE THREAD

**Issue by Elisedlund-ericsson** [bsorrentino/maven-confluence-plugin#283]
Ran into issue #282 which is already solved in 7.9 which unfortunately is not available in any decent public repositories so it can be used.

There's is an issue with 7.9 not being available however:
https://search.maven.org/artifact/org.bsc.maven/confluence-reporting-maven-plugin
https://mvnrepository.com/artifact/org.bsc.maven/confluence-reporting-maven-plugin

Strangely enough I was able to fetch 7.9-SNAPSHOT and can confirm that the fix solves the issue with "%" in md files. (also figured out the "%%" workaround)

I would like however to use 7.9 and not 7.9-SNAPSHOT or 7.8+%% workaround so please lookinto the issue with 7.9 not being available

**Comment by bsorrentino** [comment]
Hello @elisedlund-ericson thanks for the feedback

It seems strange to me, I will check on the Sonatype side

**Comment by bsorrentino** [comment]
Hi @Elisedlund-ericsson fix it!

the `7.9` official release is available from pubic [Sonatype repo](https://central.sonatype.com/artifact/org.bsc.maven/confluence-reporting-maven-plugin/7.9/versions) as usual

**Comment by Elisedlund-ericsson** [comment]
verified it!
thanks for the quick turnaround time 🥇
