### ISSUE TITLE
Image markup seems to be not working

### ISSUE THREAD

**Issue by FromirDread** [bsorrentino/maven-confluence-plugin#286]
Hi,
I'm using following markup annotation
`![bla.drawio.png](bla.drawio.png)`

with these plugin versions
`<confluence.maven.plugin.version>7.11</confluence.maven.plugin.version><confluence.maven.commonmark.version>7.11</confluence.maven.commonmark.version>`

After plugin was creating confluence page, I can only see "unknown attachment" but in all of my markup clients it's working fine?
Do I something wrong here?

**Comment by bsorrentino** [comment]
Hi @FromirDread 

do you see `unknown attachment` when render page in Confluence or in the generated wiki ?

**Comment by FromirDread** [comment]
Hi @bsorrentino,
we´re only using confluence pages and not wiki.

I have also no root access to our confluence server, in case you need a logfile / event log or something like that I have to request it from sysadmin.

**Comment by bsorrentino** [comment]
> Hi @bsorrentino, we´re only using confluence pages and not wiki.
> 
> I have also no root access to our confluence server, in case you need a logfile / event log or something like that I have to request it from sysadmin.

Probably I've not formulated well the question, however if on the page you see `unknown attachment` probably you miss to deploy attachment file `bla.drawio.png`

**Comment by FromirDread** [comment]
What do you mean by "deploy attachment file" ?
I would assume files will be uploaded during sync?

In theorie,  I would maintain everything in git and sync it to confluence

**Comment by bsorrentino** [comment]
> What do you mean by "deploy attachment file" ? I would assume files will be uploaded during sync?
> 
> In theorie, I would maintain everything in git and sync it to confluence

Sure it is so. Again, if you could provide me a simple sample I could help you to understand why it happen

**Comment by bsorrentino** [comment]
you must based on [site.xml](http://bsorrentino.github.io/maven-confluence-plugin/site_xml_guide.html)

below a minimal example that implies that `my_fisrt_page.md` and `bla.drawio.png` are in the same folder (tipically `${basedir}/src/site/confluence`)

```xml
<?xml version="1.0" encoding="UTF-8"?>

<bsc:site
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:bsc='https://github.com/bsorrentino/maven-confluence-plugin'
    xsi:schemaLocation='https://github.com/bsorrentino/maven-confluence-plugin https://raw.githubusercontent.com/bsorrentino/maven-confluence-plugin/master/schemas/site-schema-6.0.xsd'>
    <home name="my first page" uri="my_fisrt_page.md">

        <attachment name="bla.drawio.png" uri="bla.drawio.png" comment="" contentType="image/x-png" ></attachment>
    </home>

</bsc:site>
```

for further details take a look to documentation

**Comment by FromirDread** [comment]
I have already checked it in the meantime.
My assumption was correct.
Thx for you help :-)
