### ISSUE TITLE
Curly braces in table recognized as macro

### ISSUE THREAD

**Issue by krokiet** [bsorrentino/maven-confluence-plugin#295]
Hello,

I use readme file as a place to describe configuration options and since there is a lot of those I put them in a table. The problem is that some configuration options default values have curly braces in them (or example regex values) - {0,128}, {anything} etc.

```
| Property  | Default   | Required | Description                                   | Example |
|-----------|-----------|----------|-----------------------------------------------|---------|
| someEntry | `{0,128}` | false    | value that is being misinterpreted as a macro | -       |
```

Those result in:
`"message":"com.atlassian.confluence.api.service.exceptions.InternalServerException: com.atlassian.confluence.content.render.xhtml.migration.exceptions.UnknownMacroMigrationException: The macro '0,128' is unknown."}`

I cannot escape the entire value in any way. I can add '\\' before each curly brace but it would cause the regex to be invalid in readme file (while being correct in confluence).

The value is correctly considered to be a text if it is outside of the table.

Is there any option to put such values in a table so that it is not considered a macro?
I am on the 7.12 version of the plugin.

**Comment by bsorrentino** [comment]
Hi @krokiet thanks for feedback 

From your valuable analysis probably I've to apply the same encoder function  that use for simple text also on text inside a cell

I'll working on soon

**Comment by krokiet** [comment]
@bsorrentino That was a super fast fix. I will try it out tomorrow. Thank you very much for such a quick response and fix!

**Comment by bsorrentino** [comment]
Hi @krokiet  release `7.13` is out with requested fix!

**Comment by krokiet** [comment]
@bsorrentino The new version works like a charm. Thank you again!
