### ISSUE TITLE
add builtin support for plantUML

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bsorrentino/maven-confluence-plugin#70]
```

Idea is to use https://github.com/TimMoore/mojo-executor to convert plantUML 
files to images and attach them to page
```

Original issue reported on code.google.com by `bartolom...@gmail.com` on 16 Jul 2014 at 5:29

**Comment by bsorrentino** [comment]
Refer to [PlantUML & Maven - Enrich your project's documentation](http://soulsoftware-bsc.blogspot.it/2014/01/plantuml-maven-enrich-your-projects.html)
