### ISSUE TITLE
move docs from codehaus

### ISSUE THREAD

**Issue by qwazer** [bsorrentino/maven-confluence-plugin#77]
Site http://docs.codehaus.org/display/MVNCONFSITE is dead.
Maybe ask Atlassian to provide confluence hosting for this plugin?

**Comment by bsorrentino** [comment]
Hi 

Thx for feedback

 Actually I used codehaus just to show plugin's documentation in confluence format (eat-your-food approach). The official documentation is [here](http://bsorrentino.github.io/maven-confluence-plugin/)

I didn't know that codehaus hosting was discontinued :-(

Anyway I think to try with Atlassian as you suggest

**Comment by bsorrentino** [comment]
I've move the confluence docs on my public space [here] (http://support.softphone.it/confluence/display/~bsorrentino/confluence-reporting-maven-plugin-4.4)

**Comment by qwazer** [comment]
Thanks!
