### ISSUE TITLE
Confluence Serialization of lists is broken

### ISSUE THREAD

**Issue by gmuecke** [bsorrentino/maven-confluence-plugin#89]
Hi, 
when generating a page with a bullet list, everything following the list is also part of the list as the list is not properly terminated by a new line ('\n'). 
Further there is no support for numbered lists yet.

**Comment by bsorrentino** [comment]
fixed in pull request [fix for issue #89](https://github.com/bsorrentino/maven-confluence-plugin/pull/90)
