### ISSUE TITLE
scm web access not shown as actual link

### ISSUE THREAD

**Issue by ractoc** [bsorrentino/maven-confluence-plugin#91]
In my POM I have the following as my scm URL for web access, I've replaced the actual hostname and repository name with placeholders since they are not relevant and it's a private repository.

`<url>https://{Hostname}/g/?p={repository}.git</url>`

When I create the confluence page, in de SCM - Web Access, I don't see a link which takes me directly to the git web access page, but I see a code block with no format containing:
`[https://{Hostname}/g/?p={repository}.git|https://{Hostname}/g/?p={repository}.git]`

Is it possible to change this to support an actual link?

**Comment by bsorrentino** [comment]
Absolutely, I'll investigate why happen asap 

Thanks for feedback

**Comment by ractoc** [comment]
Great, let me know when there's a new version available with the fix so I can test it for you.

**Comment by bsorrentino** [comment]
I've deployed the release **4.4.4-SNAPSHOT **

the snapshot repository is https://oss.sonatype.org/content/repositories/snapshots

Please, test it and let me know

**Comment by ractoc** [comment]
It works great, thanks.Shouldn't be a problem to create the real release and upload it to the central maven repo.

**Comment by bsorrentino** [comment]
Thanks for feedback

No problem, I'll arrange a official release (4.4.4) asap

**Comment by bsorrentino** [comment]
I've released version **4.5** to maven central repo
