### ISSUE TITLE
Make it work with multi-module projects

### ISSUE THREAD

**Issue by davidkarlsen** [bsorrentino/maven-confluence-plugin#92]
Hi.

The plugin seems to do exactly what I am looking for - distribute my maven site into confluence.
But I cannot get it to work properly with multi-module projects? The same wiki page seems to be overwritten per module deployment, which I would expect the sub-modules to be child pages under the topmost one.

What am I doing wrong?

**Comment by bsorrentino** [comment]
Hi, thanks for interest 

It is possible to achieve what you want to do but using some  configuration tricks (that I discourage)

I use, such plugin, to deploy documentation of my projects and I suggest, firstly to use [site definition feature ](https://github.com/bsorrentino/maven-confluence-plugin/wiki/Use-Site-Definition) secondly I'd create a page in Confluence that will be the common *parent page* so all submodules will publish a page tree starting from that

However another "best practice" could be create a new module (or parent project itself) that will contain all documentation
